# Generated by Django 2.1.2 on 2018-11-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('rut_adop', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nomb_adoptante', models.CharField(max_length=20)),
                ('apaterno_adoptante', models.CharField(max_length=15)),
                ('correo_adoptante', models.EmailField(max_length=254)),
                ('edad_adoptante', models.IntegerField()),
                ('tel_adoptante', models.CharField(max_length=12)),
            ],
        ),
    ]
