# Generated by Django 2.0.9 on 2018-11-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_adoptante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='correo_adoptante',
            field=models.EmailField(max_length=55),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='edad_adoptante',
            field=models.IntegerField(max_length=2),
        ),
    ]
